# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2

      - id: openvscodeServer
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gitpod-io/openvscode-server
          excludes: prerelease, draft, nightly
          
      - name: Get last bunddle
        run: |
          wget https://github.com/gitpod-io/openvscode-server/releases/download/${{ steps.openvscodeServer.outputs.release }}/${{ steps.openvscodeServer.outputs.release }}-linux-x64.tar.gz
          tar -xzf ${{ steps.openvscodeServer.outputs.release }}-linux-x64.tar.gz
          mv ${{ steps.openvscodeServer.outputs.release }}-linux-x64 openvscode-server-termux
          rm -rf openvscode-server-termux/node openvscode-server-termux/node_modules
          chmod -R 777 openvscode-server-termux
            
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64

      - uses: addnab/docker-run-action@v3
        with:
          image: xeffyr/termux:aarch64
          options: -v ${{ github.workspace }}:/work --privileged=true
          run: |
            cp -R /work/openvscode-server-termux /work/server
            cat /work/openvscode-server-termux/package.json
            mkdir -p /work/server/node_modules
            mkdir -p /work/openvscode-server-termux/node_modules
            rm -rf /work/openvscode-server-termux/package.json
            cd /work/openvscode-server-termux
            

      - name: Clean useless files
        run: |
          chmod -R 777 openvscode-server-termux
          cd openvscode-server-termux
          find . -name "*.map" | xargs rm
          find . -name "*[^\.][^d].ts" | xargs rm
          cd ../
          tar -czvf openvscode-server-termux.tar.gz openvscode-server-termux

      - uses: actions/upload-artifact@v2
        with:
          name: openvscode-server-termux
          path: openvscode-server-termux.tar.gz
